label: Новости
display:
  news_page:
    display_options:
      menu:
        title: Новости
  default:
    display_options:
      title: Новости
      filters:
        field_region_value:
          expose:
            label: Регион
        field_category_target_id:
          expose:
            label: Категория
