label: 'Сторінка схеми блоків'
tips:
  block-layout:
    label: 'Схема блоків'
    body: 'Блоки  – це поля вмісту, відтворювані в певній частині або області вебсторінки, які можуть відображатися в областях (наприклад, нижній колонтитул або бічна панель) на сторінці.'
  place-block:
    label: 'Розміщення блоків'
    body: 'Будь-який спеціальний або внесений блок можна додати до певної області, натиснувши кнопку Розмістити блок. Також натисканням цієї кнопки можна створити новий блок.'
  block-region:
    label: 'Область блоку'
    body: 'Вкажіть або змініть область блоку, натиснувши тут. З''явиться розкривний список з усіма доступними областями. Один блок можливо розмістити у декількох областях.'
  configure-block:
    label: 'Налаштувати блок'
    body: 'Натиснувши кнопку "Налаштувати" можна продовжувати редагувати вміст блоку, розібратися з налаштуваннями видимості та навіть змінити розташування блоку в темі.'
  custom-block-library:
    label: 'Бібліотека власних блоків'
    body: 'Екран керування блоками також має ще одну вкладку вгорі, яка використовується для додавання Власних блоків. Назва цієї вкладки - "Бібліотека власних блоків". Ця вкладка зрештою містить посилання для додавання власних блоків.'
