_core:
  default_config_hash: CXhei_vpaZk-3f_Mj2cH0YmpK-ZpKHoSzVA3yZrDq0g
definitions:
  contact__site_page:
    weight: -49
    menu_name: footer
    parent: ''
    enabled: true
    expanded: false
